#db.driverLocation=C:/Users/sifu/.m2/repository/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar
db.driverLocation=C:/Users/yhx12/.m2/repository/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar
db.driverClassName=com.mysql.jdbc.Driver
db.url=jdbc:mysql://123.207.110.102:3306/zb?characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
db.username=root
db.password=Bst123456789


